language: ruby
sudo: required
rvm:
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - 2.4.1
cache: bundler
cache:
  directories:
  - $TEST_DIR/vendor/bundle
services:
  - docker
before_install:
  - ./build/travis/before_install.sh
env:
  global:
    - secure: "UyygtUDLvV2+14mEG6Pddo/deLazXc2Hit63KlbZ26Pi8cxbr1FeDUBi4WFVWlFh01smKe5mO+kk/4k06aSdolcTC59QUsltRrsINmsxj/BS66L7JbWP8/yPQP1drE6CH5oh6t1JAchuK19bLUOK9Tycn0J2VufW69ckw3D+rqU=" # DOCKER_HUB_PASSWORD
    - secure: "YKHqxWKFfrhJoQ5ptfgnByGNdcRLcQVpI22EGjU5WWzQrUw3Frq8+zsRmSNjzF6qEi5oXfxzxUaOItzY8W8bkWUVHCaVGalfyK+C4ad55n8ZpP2cZkOJtenocPhhUTRFwOuAZsUYCI+hXroMyoBUsnu4AJqpkYVimlNblOdcWoA=" # RUBYGEMS_USER
    - secure: "UlPV+vpgZnzb1zRgGlk6U0/i6B22W+YzUDjgUZRFmLobBzZgDoVcVZUIKRjVanFuc75sd/GV2SKm39RTV/ihJ5I5BAiL20E4XtSf52w1oX2PiAXDeLiW6+4flcs8JiejGdnJplYJwWkls39Sdq/KOR+J3erpxI70JlK19/oRtOc=" # BINTRAY_USER
    - secure: "CjBV1vcOnzkz2lDJiyrVaHiJf9ukZAisF3Jglp7k/eFSjBs13I0klSurPL0Lkm+R8/lF98EW+C79jbSsQ/bYpyaGUxakJ2pY0i5r7JP4YBK5MKmLIURUuiRU358ywp1z/T41ldqyK78OoyGt9cmSilTx1f1FVN0rAqQtsALHZVs=" # BINTRAY_KEY
    - secure: "kj4oS3to1iKpJBbph2VHSnTauvniP6F/RaN6Smn60ZFJCiJHST+Yq6GHONIxb9aNTpyYJWlYA0A1ReqVurS/T3puIYYZvPW6QQs2llB2I2GwAyPeSJSOX2z0vQtQq6ybdeROUuJLHkGL4zCI4V5QlJgSnmSOjvdiEZPtxWfy384=" # GITHUB_TOKEN
    - DOCS_GA=UA-60024048-1
    - DOCS_HS=2126125
  matrix:
    - TEST_DIR=agent
    - TEST_DIR=cli
    - TEST_DIR=server
matrix:
    exclude:
    - rvm: 2.1.10
      env: TEST_DIR=agent
    - rvm: 2.1.10
      env: TEST_DIR=server
    - rvm: 2.2.6
      env: TEST_DIR=agent
    - rvm: 2.2.6
      env: TEST_DIR=server
    - rvm: 2.3.3
      env: TEST_DIR=server
    - rvm: 2.3.3
      env: TEST_DIR=agent
script: ./build/travis/test.sh
deploy:
  - provider: script
    script: "rvm $TRAVIS_RUBY_VERSION do $TRAVIS_BUILD_DIR/build/travis/deploy_gem.sh"
    on:
      tags: true
      condition: $TEST_DIR = cli && $TRAVIS_OS_NAME = linux
      rvm: 2.3.3
      repo: kontena/kontena
  - provider: script
    script: "rvm $TRAVIS_RUBY_VERSION do $TRAVIS_BUILD_DIR/build/travis/deploy_omnibus.sh"
    on:
      tags: true
      condition: $TEST_DIR = cli && $TRAVIS_OS_NAME = linux
      rvm: 2.4.1 # separate from deploy_gem, ideally after
      repo: kontena/kontena
  - provider: script
    script: "rvm $TRAVIS_RUBY_VERSION do $TRAVIS_BUILD_DIR/build/travis/deploy.sh"
    on:
      tags: true
      condition: $TEST_DIR = server && $TRAVIS_OS_NAME = linux
      rvm: 2.4.1
      repo: kontena/kontena
