language: ruby
rvm:
  - 2.0.0-p648
  - 2.1.8
  - 2.2.3
  - 2.3.1
cache: bundler
addons:
  apt:
    sources:
      - mongodb-3.0-precise
    packages:
      - mongodb-org-server
env:
  - TEST_DIR=server
  - TEST_DIR=agent
  - TEST_DIR=cli
matrix:
  exclude:
    - rvm: 2.0.0-p648
      env: TEST_DIR=server
    - rvm: 2.1.8
      env: TEST_DIR=server
    - rvm: 2.2.3
      env: TEST_DIR=server
    - rvm: 2.0.0-p648
      env: TEST_DIR=agent
    - rvm: 2.1.8
      env: TEST_DIR=agent
    - rvm: 2.2.3
      env: TEST_DIR=agent
script: CI=true cd $TEST_DIR && bundle install && bundle exec rspec spec/
