language: ruby
sudo: required
cache:
  bundler: true
  directories:
    - $TEST_DIR/vendor/bundle
before_install:
  # Pull images to get layers
  - if [[ "$TEST_DIR" = "test" ]]; then docker pull kontena/agent:latest; docker pull kontena/server:latest; docker pull kontena/cli:latest; docker pull mongo:3.4; fi
  # Run before_install script
  - ./build/travis/before_install.sh

services:
  - docker

bundler_args: --without development
env:
  global:
    - secure: "UyygtUDLvV2+14mEG6Pddo/deLazXc2Hit63KlbZ26Pi8cxbr1FeDUBi4WFVWlFh01smKe5mO+kk/4k06aSdolcTC59QUsltRrsINmsxj/BS66L7JbWP8/yPQP1drE6CH5oh6t1JAchuK19bLUOK9Tycn0J2VufW69ckw3D+rqU=" # DOCKER_HUB_PASSWORD
    - secure: "YKHqxWKFfrhJoQ5ptfgnByGNdcRLcQVpI22EGjU5WWzQrUw3Frq8+zsRmSNjzF6qEi5oXfxzxUaOItzY8W8bkWUVHCaVGalfyK+C4ad55n8ZpP2cZkOJtenocPhhUTRFwOuAZsUYCI+hXroMyoBUsnu4AJqpkYVimlNblOdcWoA=" # RUBYGEMS_USER
    - secure: "UlPV+vpgZnzb1zRgGlk6U0/i6B22W+YzUDjgUZRFmLobBzZgDoVcVZUIKRjVanFuc75sd/GV2SKm39RTV/ihJ5I5BAiL20E4XtSf52w1oX2PiAXDeLiW6+4flcs8JiejGdnJplYJwWkls39Sdq/KOR+J3erpxI70JlK19/oRtOc=" # BINTRAY_USER
    - secure: "CjBV1vcOnzkz2lDJiyrVaHiJf9ukZAisF3Jglp7k/eFSjBs13I0klSurPL0Lkm+R8/lF98EW+C79jbSsQ/bYpyaGUxakJ2pY0i5r7JP4YBK5MKmLIURUuiRU358ywp1z/T41ldqyK78OoyGt9cmSilTx1f1FVN0rAqQtsALHZVs=" # BINTRAY_KEY
    - secure: "kj4oS3to1iKpJBbph2VHSnTauvniP6F/RaN6Smn60ZFJCiJHST+Yq6GHONIxb9aNTpyYJWlYA0A1ReqVurS/T3puIYYZvPW6QQs2llB2I2GwAyPeSJSOX2z0vQtQq6ybdeROUuJLHkGL4zCI4V5QlJgSnmSOjvdiEZPtxWfy384=" # GITHUB_TOKEN
    - DOCS_GA=UA-60024048-1
    - DOCS_HS=2126125
    - ALLOW_FAILURES=false
stages:
  - name: test
  - name: test e2e
    if: type = pull_request OR type = cron
  - name: deploy gem
    if: tag IS present
  - name: deploy omnibus
    if: tag IS present
  - name: deploy images
    if: tag IS present
jobs:
  fast_finish: true
  allow_failures:
    - env:
      - TEST_DIR=cli
      - ALLOW_FAILURES=true
  include:
    - stage: test
      script: ./build/travis/test.sh
      rvm: 2.2
      env: TEST_DIR=cli
      if: type = pull_request
    - stage: test
      script: ./build/travis/test.sh
      rvm: 2.3
      env: TEST_DIR=cli
      if: type = pull_request
    - stage: test
      script: ./build/travis/test.sh
      rvm: 2.4
      env: TEST_DIR=cli
    - stage: test
      script: ./build/travis/test.sh
      rvm: 2.5
      env: TEST_DIR=cli
      if: type = pull_request
    - stage: test
      script: ./build/travis/test.sh
      rvm: 2.4
      env: TEST_DIR=agent
    - stage: test
      script: ./build/travis/test.sh
      rvm: 2.4
      env: TEST_DIR=server
    - stage: test e2e
      script: ./build/travis/test_e2e.sh
      rvm: 2.4
      env:
        - TEST_DIR=test
    - stage: deploy gem
      script: "rvm $TRAVIS_RUBY_VERSION do $TRAVIS_BUILD_DIR/build/travis/deploy_gem.sh"
      tags: true
      repo: kontena/kontena
      rvm: 2.3
      env: TEST_DIR=cli
    - stage: deploy omnibus
      script: "rvm $TRAVIS_RUBY_VERSION do $TRAVIS_BUILD_DIR/build/travis/deploy_omnibus.sh"
      tags: true
      repo: kontena/kontena
      rvm: 2.4
      env: TEST_DIR=cli
    - stage: deploy omnibus
      script: "rvm $TRAVIS_RUBY_VERSION do $TRAVIS_BUILD_DIR/build/travis/deploy_omnibus_macos.sh"
      tags: true
      os: osx
      repo: kontena/kontena
      rvm: 2.4
      env: TEST_DIR=cli
    - stage: deploy images
      script: "rvm $TRAVIS_RUBY_VERSION do $TRAVIS_BUILD_DIR/build/travis/deploy.sh"
      tags: true
      repo: kontena/kontena
      rvm: 2.4
      env: TEST_DIR=server
