api:
  build: .
  dockerfile: Dockerfile
  ports:
    - 80:9292
  environment:
    - RACK_ENV=production
    - MONGODB_URI=mongodb://mongodb:27017/kontena_development
    - VAULT_KEY=jkfldsjkflsdajfaklsjfklasdjfklas
    - VAULT_IV=kfsdfopweu09fewjlhfksdjifjpoweop
    - ACME_ENDPOINT=https://acme-staging.api.letsencrypt.org/
    - INITIAL_ADMIN_CODE=initialadmincode
    - RBTRACE=true
  links:
   - mongodb
mongodb:
  image: mongo:3.0
  command: mongod --smallfiles
