agent:
  container_name: kontena-agent
  build: ..
  dockerfile: Dockerfile.agent
  env_file: .env
  net: host
  environment:
    - KONTENA_PEER_INTERFACE=eth1
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
